<h1>Users</h1>
<?php if (!empty($flash)): ?>
<p style="color: green"><?= $flash['success'][0]?></p>
<hr>
<?php endif; ?>
<div>
  <form action="/users" method="get">
    <input type="search" name="term" value="<?= htmlspecialchars($term) ?>" />
    <button type="submit">Search</button>
  </form>
</div>
<hr>
<?php if (empty($users)): ?>
<p>Nothing to display, sorry. :(</p>
<?php endif; ?>
<ul>
  <?php foreach ($users as $user): ?>
    <li><i><?= htmlspecialchars($user['nickname'])?></i></li>
  <?php endforeach; ?>
</ul>
